# Generated by Django 6.0.3 on 2026-06-10 06:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_download_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
