# Generated by Django 6.0.3 on 2026-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_download_file_alter_requirement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
