# Generated by Django 6.0.3 on 2026-06-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_popupnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
