# Generated by Django 6.0.3 on 2026-04-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programdetail',
            options={},
        ),
        migrations.RenameField(
            model_name='programdetail',
            old_name='section_title',
            new_name='page_title',
        ),
        migrations.RemoveField(
            model_name='programdetail',
            name='content',
        ),
        migrations.RemoveField(
            model_name='programdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='programdetail',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='program_detail_media/'),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='revised_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='section1_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='section1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='section2_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='section2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='section3_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='section3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='programs.program'),
        ),
    ]
