# Generated by Django 6.0.3 on 2026-04-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='programs.program'),
        ),
    ]
