# Generated by Django 6.0.3 on 2026-04-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_programdetail_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='programs.program'),
        ),
    ]
