# Generated by Django 6.0.3 on 2026-04-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_programdetail_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='programs.program'),
        ),
    ]
