# Generated by Django 6.0.3 on 2026-06-07 05:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_programdetail_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='section1_content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='section2_content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='section3_content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
